name: Test
on: [push, pull_request]
jobs:
  run-test:
    name: Test
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout branch (${{ github.ref }})
        uses: actions/checkout@master
      - name: Configure git
        run: |
          git config user.name "Action"
          git config user.email "rafegoldberg@gmail.com"
      - name: Setup node (v${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: |
          npm ci
      - name: Run Tests
        run: |
          npm test